add getDate() method
personnummer/java pull request #82
Opened 2023-03-12 10:36 UTC by cbhat5

…m the Personnummer object

**Type of change**

- [ ✅] New feature
- [ ] Bug fix
- [ ] Security patch
- [ ✅] Documentation update

**Description**

 
Add the getDate method

**Related issue**

#80 
**Motivation**

All good.

**Checklist**

- [ ✅] I have read the **CONTRIBUTING** document.
- [ ✅] I have read and accepted the **Code of conduct**
- [ ✅] Tests passes.
- [ ✅] Style lints passes.
- [ ✅] Documentation of new public methods exists.

2023-03-12 10:40 UTC, cbhat5 commented
Might have to change if #60 is merged.

2023-03-12 10:54 UTC, cbhat5 reviewed
Will have to change getDate() month component if #60 is merged

2023-03-12 11:46 UTC, Johannestegner requested changes
Thank you for the pull request!

The code looks good, I'd just love a check on the actual output in the tests and I'll happily merge it :)

2023-03-12 11:46 UTC, Johannestegner commented on src/test/java/PersonnummerTest.java
> +    public void testDate(PersonnummerData ssn) {
Could you add a test on the format as well just to make sure the actual dates are correct (basically just check that the passed SSN have the correct year/month/day compared to the actual date object)?

2023-03-13 12:13 UTC, cbhat5 commented
@Johannestegner The existing code with below test case sets the `fullYear` to be `2009` instead of `1909` for `separated_format`/`short format`. I create `LocalDateTime`object based on `fullYear` attribute. The base code needs to be rewritten to consider the space.
```json
{
        "integer": 0,
        "long_format": "19090527 1474",
        "short_format": "090527 1474",
        "separated_format": "090527 1474",
        "separated_long": "19090527 1474",
        "valid": false,
        "type": "ssn",
        "isMale": true,
        "isFemale": false
    }
```

2023-03-13 12:20 UTC, Johannestegner commented
When it comes to the short format, we always have to guess which century the number is for, so that one is expected.
When it comes to the separated format, if there is a `-`, the number will be seen as within the 100 year range, and a `+` over 100 years.

So the full year should be correct to use.

Easiest way to handle this in the tests would be to just check on the decade value instead of the full year in the assert :)

2023-03-13 12:22 UTC, Johannestegner commented
In the C# package, I format the value from the Date object as a `yyMMdd` value and just check them against each other, which I think is a sufficient test.

2023-03-13 12:22 UTC, cbhat5 commented
> When it comes to the short format, we always have to guess which century the number is for, so that one is expected. When it comes to the separated format, if there is a `-`, the number will be seen as within the 100 year range, and a `+` over 100 years.
> 
> So the full year should be correct to use.
> 
> Easiest way to handle this in the tests would be to just check on the decade value instead of the full year in the assert :)

Will not the short format also have a separator either of `-` or `+` instead of the ` ` in the short format?

2023-03-13 12:40 UTC, Johannestegner commented on src/test/java/PersonnummerTest.java
> +				assertEquals(expected, actual, "expected = " + expected + "\n" + "Actual = " + actual);
I was thinking checking all the four parts here, YY MM and DD.
Just against a simple format would work fine:

```
// something like...
assertEquals(ssn.longFormat.substring(2),  date.getYear() + date.getMonth() + date.getDay());
```

Although, I'd guess that the date object have some type of format function with a string value to pass (yyMMdd would do in that case I would imagine).

With that I'll happily merge the PR :)

2023-03-13 12:45 UTC, cbhat5 commented
> Aaah I double checked the meta (and then again looked at the code you shown) and that number is invalid (due to the space), so it should fail in the parse even :)

yeah, looks like an issue with regex, I added a space as an additional option, and it fails many other tests, I am not sure of the other possible patterns. Does the updated PR look fine to you? It passes the tests with `getFullYear`.

2023-03-13 12:46 UTC, cbhat5 commented on src/test/java/PersonnummerTest.java
> +				assertEquals(expected, actual, "expected = " + expected + "\n" + "Actual = " + actual);
Ok, I'll add the dates and months. I totally forgot with this century issue popping up.

2023-03-13 13:27 UTC, Johannestegner approved these changes

2023-03-13 13:27 UTC, Johannestegner commented
Yes, looks good to me! :)

Thank you for the pull request!

2023-03-13 13:28 UTC, merged